//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System__SMS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couse_Material
    {
        public int course_NO { get; set; }
        public string course_Title { get; set; }
        public Nullable<double> credit_Hours { get; set; }
        public string course_Teacher { get; set; }
    }
}
