//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System__SMS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int book_ID { get; set; }
        public string book_Title { get; set; }
        public string book_Category { get; set; }
        public Nullable<int> available_NO { get; set; }
    }
}
