//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System__SMS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int student_ID { get; set; }
        public string student_Name { get; set; }
        public string department { get; set; }
        public string phone_NO { get; set; }
        public string blood_Group { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
    }
}
